### ISSUE TITLE
Logo Design For Bus When Twin Cities

### ISSUE THREAD

**Issue by zularizal** [sweetiepiggy/Bus-When-Twin-Cities#1]
Hi @sweetiepiggy , I'm a graphic designer. I like your project, so I want to contribute by creating a free logo for your project. What do you think?

**Comment by sweetiepiggy** [comment]
Hi @zularizal ,

Thank you for your interest. I was surprised to hear from you considering the early state the project was in and wanted to wait until things were a bit more established before responding; sorry for the delay.

We have a logo now (see my avatar, svg [here](https://github.com/sweetiepiggy/Bus-When-Twin-Cities/blob/next/logo/logo.svg)) and are basically happy with it, but if you're still interested in contributing then any ideas for improvement would be welcome. In particular, at least the legacy icons could probably benefit from some lighting and shadow effects rather than the current plain #119589 background.

Here's an image of our local bus stop signs; we like the logo to be somewhat recognizable but also unique.

<img src="https://www.metrotransit.org/Data/Sites/1/media/about/improvements/shelters/busstop_tier2.jpeg" width="150"/>

**Comment by zularizal** [comment]
Yeah, I love your logo. It looks unique and cool. The logo has a good idea behind it.
Maybe if you need a logo for your other open source projects, you can contact me or tag me. I did not ask for a fee to make it. Thanks.
